{\rtf1\ansi\ansicpg1252\cocoartf2758
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 openapi: 3.0.0\
info:\
  title: Mirrulations API\
  description: An API for retrieving regulatory docket information based on search terms.\
  version: 1.0.0\
servers:\
  - url: https://api.mirrulations.com\
    description: Production server\
  - url: http://localhost:5000\
    description: Local development server\
paths:\
  /search:\
    get:\
      summary: Search for regulatory dockets\
      description: Retrieves a list of dockets related to the provided search terms, including statistics on term prevalence and comment data.\
      parameters:\
        - name: terms\
          in: query\
          description: A comma-separated list of search terms (e.g., `marijuana,psychedelics`).\
          required: true\
          schema:\
            type: string\
        - name: sort\
          in: query\
          description: Sort order for results (`relevance`, `comments`).\
          required: false\
          schema:\
            type: string\
            enum: [relevance, comments]\
            default: relevance\
      responses:\
        '200':\
          description: A list of dockets matching the search terms.\
          content:\
            application/json:\
              schema:\
                type: array\
                items:\
                  type: object\
                  properties:\
                    docketId:\
                      type: string\
                      example: DEA-2024-0059\
                    title:\
                      type: string\
                      example: Schedules of Controlled Substances: Rescheduling of Marijuana\
                    docketScore:\
                      type: number\
                      format: float\
                      example: 95.6\
                      description: A measure of how prevalent the search terms are in the docket and supporting documents.\
                    commentMatchCount:\
                      type: integer\
                      example: 42852\
                      description: The number of comments that refer to the search terms.\
                    commentTotalCount:\
                      type: integer\
                      example: 42923\
                      description: The total number of comments for the docket.\
        '400':\
          description: Invalid request (e.g., missing or malformed parameters).\
        '500':\
          description: Internal server error.\
  /health:\
    get:\
      summary: Check API health\
      description: Returns the current status of the API.\
      responses:\
        '200':\
          description: API is operational.\
          content:\
            application/json:\
              schema:\
                type: object\
                properties:\
                  status:\
                    type: string\
                    example: UP\
                  error:\
                    type: string\
                    nullable: true\
                    example: null\
                  timestamp:\
                    type: string\
                    format: date-time\
                    example: 2025-01-26T18:00:00Z\
        '500':\
          description: API is down or experiencing issues.\
\
components:\
  schemas:\
    Docket:\
      type: object\
      properties:\
        docketId:\
          type: string\
          example: DEA-2024-0059\
        title:\
          type: string\
          example: Schedules of Controlled Substances: Rescheduling of Marijuana\
        docketScore:\
          type: number\
          format: float\
          example: 95.6\
        commentMatchCount:\
          type: integer\
          example: 42852\
        commentTotalCount:\
          type: integer\
          example: 42923}